spring.application.name=TaskMaster
server.port = 4000

# MySQL DB config
spring.datasource.url=jdbc:mysql://localhost:3306/taskmasterapplication?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Spring Security
spring.security.user.name=user
spring.security.user.password=$2a$11$iyU1WaiYPgmfJHqQa5GOTObiXkieo8VmxwKF0PcxPgf0pBk1rHN92

